blogs:
- dochii-blog
- '1243'
- '1'
- '2'
- '3'
- blog123
- '6'
- '7'
- blog3
footer:
  copyright: © {year} 我们的团队博客
  powered_by: Powered by HTML + CSS + JS
git:
  repo_url: git@github.com:rongyicheng23-afk/blog.git
  website_url: https://rongyicheng23-afk.github.io/blog
info:
  author: Leamon Lee
  email: leamon@example.com
  motto: 记录与分享
  website_name: DOCHII Blog2
path: ../
theme:
  script: ../src/dtheme/dutils.js
  style: ../src/dtheme/dstyle.css
